// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdxZcG2knmBYRXgcd-o0_3hcXtR8m00ic',
    appId: '1:1077651590789:web:f44379e4b04cddd9be63ec',
    messagingSenderId: '1077651590789',
    projectId: 'healthsnap-6f17a',
    authDomain: 'healthsnap-6f17a.firebaseapp.com',
    storageBucket: 'healthsnap-6f17a.firebasestorage.app',
    measurementId: 'G-SDY9VQ4FH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhub-Wxw94WRZkD-UXk9OTvlWqN1NGgPU',
    appId: '1:1077651590789:android:5c26df221d8a82d0be63ec',
    messagingSenderId: '1077651590789',
    projectId: 'healthsnap-6f17a',
    storageBucket: 'healthsnap-6f17a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9PUD1QQTpsLely1a_JFXOc-w7EFkw0qw',
    appId: '1:1077651590789:ios:7188f15cc2c52865be63ec',
    messagingSenderId: '1077651590789',
    projectId: 'healthsnap-6f17a',
    storageBucket: 'healthsnap-6f17a.firebasestorage.app',
    iosBundleId: 'com.example.healthsnapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9PUD1QQTpsLely1a_JFXOc-w7EFkw0qw',
    appId: '1:1077651590789:ios:7188f15cc2c52865be63ec',
    messagingSenderId: '1077651590789',
    projectId: 'healthsnap-6f17a',
    storageBucket: 'healthsnap-6f17a.firebasestorage.app',
    iosBundleId: 'com.example.healthsnapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdxZcG2knmBYRXgcd-o0_3hcXtR8m00ic',
    appId: '1:1077651590789:web:b43a201d8e45163fbe63ec',
    messagingSenderId: '1077651590789',
    projectId: 'healthsnap-6f17a',
    authDomain: 'healthsnap-6f17a.firebaseapp.com',
    storageBucket: 'healthsnap-6f17a.firebasestorage.app',
    measurementId: 'G-NWPBNPYKBB',
  );
}
